# Default enviroment set up with port 8081 - redirected here from web server
# as the application default port: Port 8080 set as internal port
server:
    address: 127.0.0.1
    port: ${appPort:8082}
    internalPort: 8080
---
# Local(dev) environment port set up
spring:
    profiles: local
server:
    address: 127.0.0.1
    port: ${appPort:8081}
    internalPort: 8080
---
# Test environment port set up
spring:
    profiles: test
server:
    address: 192.168.1.120
    port: ${appPort:8085}
    internalPort: 8080
---
# Production environment port set up
spring:
    profiles: production
server:
    address: 192.168.1.120
    port: ${appPort:8084}
    internalPort: 8080
